# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'expense.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets, QtSql


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(698, 299)
        MainWindow.setStyleSheet("background-color: #02886f;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setDate(QtCore.QDate.currentDate())
        self.dateEdit.setGeometry(QtCore.QRect(500, 30, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 30, 151, 21))
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 82, 151, 21))
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 143, 151, 20))
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(500, 80, 161, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 200, 75, 23))
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(500, 150, 161, 20))
        self.lineEdit_2.setTabletTracking(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 200, 151, 23))
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        label_box_color = "background-color: #faeaeb;"
        self.dateEdit.setStyleSheet(label_box_color)
        self.lineEdit.setStyleSheet(label_box_color)
        self.lineEdit_2.setStyleSheet(label_box_color)
        label_background_color = "background-color: #faeaeb;"
        self.label.setStyleSheet(label_background_color)
        self.label_2.setStyleSheet(label_background_color)
        self.label_3.setStyleSheet(label_background_color)
        
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(590, 200, 75, 23))
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        button_background_color = "background-color: #faeaeb;"
        self.pushButton.setStyleSheet(button_background_color)
        self.pushButton_2.setStyleSheet(button_background_color)
        self.pushButton_4.setStyleSheet(button_background_color)
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
      

        self.pushButton.clicked.connect(self.submit_button_clicked)
        self.pushButton_4.clicked.connect(self.clear_button_clicked)
        self.pushButton_2.clicked.connect(self.view_expense_button_clicked)

        self.db = QtSql.QSqlDatabase.addDatabase("QSQLITE")
        self.db.setDatabaseName("Expense.db")
        if not self.db.open():
            QtWidgets.QMessageBox.critical(None, "Database Error", "Could not open database")
        query = QtSql.QSqlQuery()
        query.exec_("CREATE TABLE IF NOT EXISTS Expenses (id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT, name TEXT, expense TEXT)")

        
    def submit_button_clicked(self):
        date = self.dateEdit.date().toString(QtCore.Qt.ISODate)
        name_of_expense = self.lineEdit.text()
        expense = self.lineEdit_2.text()

        if not (name_of_expense and expense):
            QtWidgets.QMessageBox.warning(None, "Error", "Please enter all fields.")
            return
        query = QtSql.QSqlQuery()
        query.prepare("INSERT INTO Expenses (date, name, expense) VALUES (?, ?, ?)")
        query.addBindValue(date)
        query.addBindValue(name_of_expense)
        query.addBindValue(expense)
        if not query.exec_():
            QtWidgets.QMessageBox.critical(None, "Database Error", "Could not add data to the database")
        else:
            QtWidgets.QMessageBox.information(None, "Success", "Data added successfully")
        
    def clear_button_clicked(self):
        self.dateEdit.setDate(QtCore.QDate.currentDate())
        self.lineEdit.clear()
        self.lineEdit_2.clear()

    def view_expense_button_clicked(self):
        self.expenses_window = QtWidgets.QMainWindow()
        self.ui_expenses = Ui_ExpensesWindow()
        self.ui_expenses.setupUi(self.expenses_window)

        model = QtSql.QSqlTableModel()
        model.setTable("Expenses")
        model.select()

        self.ui_expenses.tableView.setModel(model)
        self.ui_expenses.clearButton.clicked.connect(self.clear_expenses_button_clicked)
        self.expenses_window.show()

        
        

    def clear_expenses_button_clicked(self):
        reply = QtWidgets.QMessageBox.question(None, 'Clear Expenses', 'Are you sure you want to clear all expenses?', QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.No)
        if reply == QtWidgets.QMessageBox.Yes:
            query = QtSql.QSqlQuery()
            query.exec_("DELETE FROM Expenses")
            query_reset_sequence = QtSql.QSqlQuery()
            query_reset_sequence.exec_("DELETE FROM sqlite_sequence WHERE name='Expenses'")

            model = self.ui_expenses.tableView.model()
            model.select()
    
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Expense Tracker"))
        self.label.setText(_translate("MainWindow", "DATE"))
        self.label_2.setText(_translate("MainWindow", "NAME OF EXPENSE"))
        self.label_3.setText(_translate("MainWindow", "EXPENSE"))
        self.pushButton.setText(_translate("MainWindow", "SUBMIT"))
        self.lineEdit_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "VIEW EXPENSES"))
        
        self.pushButton_4.setText(_translate("MainWindow", "CLEAR"))

class Ui_ExpensesWindow(object):
    def setupUi(self, ExpensesWindow):
        ExpensesWindow.setObjectName("ExpensesWindow")
        ExpensesWindow.resize(550, 400)
        ExpensesWindow.setStyleSheet("background-color: #02886f;")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)

        self.centralwidget = QtWidgets.QWidget(ExpensesWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 500, 300))
        self.tableView.setObjectName("tableView")

        table_view_style = "background-color: white;"
        self.tableView.setStyleSheet(table_view_style)


        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(10, 320, 100, 30))
        self.clearButton.setFont(font)
        self.clearButton.setText("Clear Expenses")
        button_background_color = "background-color: #faeaeb;"
        self.clearButton.setStyleSheet(button_background_color)

        ExpensesWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ExpensesWindow)
        QtCore.QMetaObject.connectSlotsByName(ExpensesWindow)
        

    def retranslateUi(self, ExpensesWindow):
        _translate = QtCore.QCoreApplication.translate
        ExpensesWindow.setWindowTitle(_translate("ExpensesWindow", "Expenses"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ExpensesWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
